"""Normalize table and add last login and user role for user table

Revision ID: 08854cc1dc9f
Revises: 31c49bf4147b
Create Date: 2025-12-22 11:02:30.290645

"""
from typing import Sequence, Union
from sqlalchemy.dialects import postgresql

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08854cc1dc9f'
down_revision: Union[str, Sequence[str], None] = '31c49bf4147b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    user_role_enum = postgresql.ENUM(
        'superuser',
        'admin',
        'user',
        name='user_role'
    )
    user_role_enum.create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('device_customer_id_fkey'), 'device', type_='foreignkey')
    op.drop_column('device', 'customer_id')
    op.add_column('user', sa.Column('role', sa.Enum('superuser', 'admin', 'user', name='user_role'), nullable=False))
    op.add_column('user', sa.Column('last_login', sa.DateTime(timezone=True), nullable=True))
    op.drop_constraint(op.f('user_customer_id_fkey'), 'user', type_='foreignkey')
    op.drop_column('user', 'customer_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('customer_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('user_customer_id_fkey'), 'user', 'customer', ['customer_id'], ['id'])
    op.drop_column('user', 'last_login')
    op.drop_column('user', 'role')
    op.add_column('device', sa.Column('customer_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('device_customer_id_fkey'), 'device', 'customer', ['customer_id'], ['id'])
    # ### end Alembic commands ###
    user_role_enum = postgresql.ENUM(
        'superuser',
        'admin',
        'user',
        name='user_role'
    )
    user_role_enum.drop(op.get_bind(), checkfirst=True)