"""Rename device active col to is_online to indicate if the device is currently turn on

Revision ID: 0ab29193ed2b
Revises: 37276b376a14
Create Date: 2025-12-22 13:20:45.402333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ab29193ed2b'
down_revision: Union[str, Sequence[str], None] = '37276b376a14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device', sa.Column('is_online', sa.Boolean(), nullable=False))
    op.drop_column('device', 'active')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device', sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('device', 'is_online')
    # ### end Alembic commands ###
