"""Update User Table with Token Version for one Time Token

Revision ID: 142d3a52995a
Revises: cfdced4489e6
Create Date: 2025-12-23 02:06:37.314930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '142d3a52995a'
down_revision: Union[str, Sequence[str], None] = 'cfdced4489e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('one_time_token_version', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'one_time_token_version')
    # ### end Alembic commands ###
