"""Update device with additional field: dashboard config & machine

Revision ID: 1d5d346323f5
Revises: 80505d77537e
Create Date: 2026-01-15 12:46:51.244373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d5d346323f5'
down_revision: Union[str, Sequence[str], None] = '80505d77537e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device', sa.Column('machine', sa.String(), nullable=True))
    op.add_column('device', sa.Column('data_interval', sa.Integer(), nullable=False))
    op.add_column('device', sa.Column('dashboard_config', sa.JSON(), nullable=True))
    op.alter_column('device', 'department_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('mqtt_user', 'customer_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mqtt_user', 'customer_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('device', 'department_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.drop_column('device', 'dashboard_config')
    op.drop_column('device', 'data_interval')
    op.drop_column('device', 'machine')
    # ### end Alembic commands ###
