"""Update tables with created at and activate for auditing and user authentication col

Revision ID: 37276b376a14
Revises: 08854cc1dc9f
Create Date: 2025-12-22 13:09:29.896380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37276b376a14'
down_revision: Union[str, Sequence[str], None] = '08854cc1dc9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('customer', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.create_index(op.f('ix_customer_id'), 'customer', ['id'], unique=False)
    op.add_column('department', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('department', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('device', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('device', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.drop_constraint(op.f('device_department_id_fkey'), 'device', type_='foreignkey')
    op.create_foreign_key(None, 'device', 'department', ['department_id'], ['id'], ondelete='SET NULL')
    op.add_column('mqtt_user', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('mqtt_user', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('user', sa.Column('email', sa.String(), nullable=False))
    op.add_column('user', sa.Column('is_verified', sa.Boolean(), nullable=False))
    op.add_column('user', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('user', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.drop_constraint(op.f('user_username_key'), 'user', type_='unique')
    op.create_unique_constraint(None, 'user', ['email'])
    op.drop_column('user', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user', type_='unique')
    op.create_unique_constraint(op.f('user_username_key'), 'user', ['username'], postgresql_nulls_not_distinct=False)
    op.drop_column('user', 'created_at')
    op.drop_column('user', 'is_active')
    op.drop_column('user', 'is_verified')
    op.drop_column('user', 'email')
    op.drop_column('mqtt_user', 'created_at')
    op.drop_column('mqtt_user', 'is_active')
    op.drop_constraint(None, 'device', type_='foreignkey')
    op.create_foreign_key(op.f('device_department_id_fkey'), 'device', 'department', ['department_id'], ['id'])
    op.drop_column('device', 'created_at')
    op.drop_column('device', 'is_active')
    op.drop_column('department', 'created_at')
    op.drop_column('department', 'is_active')
    op.drop_index(op.f('ix_customer_id'), table_name='customer')
    op.drop_column('customer', 'created_at')
    op.drop_column('customer', 'is_active')
    # ### end Alembic commands ###
