"""Update device table default value for is_active to true

Revision ID: 583014c886c3
Revises: c64b8e1d63a7
Create Date: 2026-01-19 12:47:15.509505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '583014c886c3'
down_revision: Union[str, Sequence[str], None] = 'c64b8e1d63a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
