"""Rename token_version to one_time_token_version and added refresh token to user table

Revision ID: 80505d77537e
Revises: 142d3a52995a
Create Date: 2025-12-24 15:17:02.359383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80505d77537e'
down_revision: Union[str, Sequence[str], None] = '142d3a52995a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_customer_department', 'department', ['customer_id', 'name'])
    op.add_column('user', sa.Column('one_time_token_version', sa.Integer(), nullable=False))
    op.add_column('user', sa.Column('refresh_token_version', sa.Integer(), nullable=False))
    op.drop_column('user', 'token_version')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('token_version', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('user', 'refresh_token_version')
    op.drop_column('user', 'one_time_token_version')
    op.drop_constraint('uq_customer_department', 'department', type_='unique')
    # ### end Alembic commands ###
