"""Add distributor table and customer distributor reference

Revision ID: a7c1d4f9b3e2
Revises: 583014c886c3
Create Date: 2026-01-26 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a7c1d4f9b3e2"
down_revision: Union[str, Sequence[str], None] = "583014c886c3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "distributor",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("phone_no", sa.String(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_distributor_id"), "distributor", ["id"], unique=False)

    op.add_column("customer", sa.Column("distributor_id", sa.BigInteger(), nullable=True))
    op.create_index(op.f("ix_customer_distributor_id"), "customer", ["distributor_id"], unique=False)
    op.create_foreign_key(
        None,
        "customer",
        "distributor",
        ["distributor_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "customer", type_="foreignkey")
    op.drop_index(op.f("ix_customer_distributor_id"), table_name="customer")
    op.drop_column("customer", "distributor_id")
    op.drop_index(op.f("ix_distributor_id"), table_name="distributor")
    op.drop_table("distributor")
    # ### end Alembic commands ###
